# Generated by Django 5.0 on 2023-12-19 21:21

import django.core.validators
import django.db.models.deletion
import register.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField()),
                ('phone', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+123456789012'.", regex='^\\+\\d{12}$')])),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.RegexValidator(message='the email should be anything@ur.ac.rw', regex='^[a-zA-Z0-9._%+-]+@ur.ac.rw$')])),
                ('reference_number', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(99, message='Reference number must be at least 99.'), django.core.validators.MaxValueValidator(999, message='Reference number must be at most 999.')])),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=7, unique=True, validators=[django.core.validators.RegexValidator(message="Plate number must be entered in the correct format:'", regex='^(RA[A-H]\\d{1,3}[A-Z]$|RNP\\d{1,3}[A-Z]$|RDF\\d{1,3}[A-Z])')])),
                ('make', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=15)),
                ('man_date', models.DateField(validators=[register.models.Vehicle.validate_manufact_year_2000])),
                ('car_type', models.CharField(choices=[('M', 'Minivane'), ('S', 'Sports car'), ('O', 'others')], max_length=1)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.participants')),
            ],
        ),
    ]
